### ISSUE TITLE
Just activation web2pdf gives me an error on all pages

### ISSUE THREAD

**Issue by derpepe** [mittwald/typo3-web2pdf#18]
I just enabled web2pdf in my TYPO3 6.2.14.
All pages now show the same error: https://gist.github.com/derpepe/30c136e6d4a2c1860f33

What am I missing?

Thank you,
Peter

**Comment by martin-helmich** [comment]
Just a quick thought; did you include the static TypoScript template into your site?

**Comment by kpurrmann** [comment]
This bug is similar to #16. 
Added a quick HOTFIX #17. Should be merged soon. 
But caching seems to be the problem. I will have a look at it.

@derpepe clear all cache should work now too.

**Comment by derpepe** [comment]
Just clearing all caches with the install-tool does not work.
I'll try https://github.com/mittwald/typo3-web2pdf/pull/17 and tell you if it works for me.

Thank you for your support.

**Comment by derpepe** [comment]
Well...

Clearing caches did not change anything.

I then applied https://github.com/mittwald/typo3-web2pdf/pull/17, still no change. Cleared the caches again. No change at all.

I then tried to add the static template to the site, and it worked immediately. So @martin-helmich was right.

I still think this is a bug, just installing the extension should not break the site. What about other websites in other subtrees which do not want to use web2pdf?!

**Comment by derpepe** [comment]
I forgot to mention that I reversed the changes from the hotfix.

**Comment by martin-helmich** [comment]
I see several options here:

- Gracefully skip when the static TypoScript is missing. That way, the extension can be used on subtrees and does not break the site by installing. However, when a user forgets to add the static TypoScript, this error might be even more difficult to trace when there is not warning/notice at all.
- Display a more comprehensive error message. This will still break the site when the static template is missing, but at least the user will know what's wrong.

I actually don't have any preference on this. @pstranghoener, any thoughts?

**Comment by pstranghoener** [comment]
We should should make a gracefully skip when the static ts template is missing. This is the normale way when installing extension. We could add that to the manual. Could you do it like that @kpurrmann ?

**Comment by kpurrmann** [comment]
@pstranghoener will do that tomorrow.

**Comment by martin-helmich** [comment]
Fixed in #19.
